{
    "name": "IPAI Subscriptions",
    "version": "19.0.20251026.1",
    "license": "AGPL-3",
    "author": "InsightPulseAI",
    "website": "https://insightpulseai.net/odoo/apps/ipai_subscriptions",
    "depends": [
        "base",
        "mail",
        "account",
        "product",
        "uom",
        "contract",
        "contract_sale",
        "contract_invoice",
        "queue_job",
    ],
    "data": ["security/ir.model.access.csv", "data/sequence.xml", "data/cron.xml"],
    "installable": True,
}
