# DigitalOcean App Platform - Apache Superset Official Image
# Uses apache/superset:latest from Docker Hub
# Budget: $12/month (basic-xs tier)

name: superset-analytics
region: sgp

services:
  - name: superset
    image:
      registry_type: DOCKER_HUB
      repository: apache/superset
      tag: latest

    instance_size_slug: basic-xs
    instance_count: 1

    http_port: 8088

    health_check:
      http_path: /health
      initial_delay_seconds: 300
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    envs:
      # Database (Supabase PostgreSQL)
      - key: DATABASE_DIALECT
        scope: RUN_TIME
        value: "postgresql"

      - key: DATABASE_USER
        scope: RUN_TIME
        value: "postgres.spdtwktxdalcfigzeqrz"

      - key: DATABASE_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "SHWYXDMFAwXI1drT"

      - key: DATABASE_HOST
        scope: RUN_TIME
        value: "aws-1-us-east-1.pooler.supabase.com"

      - key: DATABASE_PORT
        scope: RUN_TIME
        value: "6543"

      - key: DATABASE_DB
        scope: RUN_TIME
        value: "postgres"

      # Redis (use local in-memory for simplicity)
      - key: REDIS_HOST
        scope: RUN_TIME
        value: "localhost"

      - key: REDIS_PORT
        scope: RUN_TIME
        value: "6379"

      # Security
      - key: SUPERSET_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "8UToEhL2C0ovd7S4maFPsi7e4mU05pqAH907G5yUaLsr9prnJdHu7+6k"

      - key: SUPERSET_ENV
        scope: RUN_TIME
        value: "production"

      - key: SUPERSET_ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "SHWYXDMFAwXI1drT"

      - key: SUPERSET_ADMIN_USERNAME
        scope: RUN_TIME
        value: "admin"

      - key: SUPERSET_ADMIN_FIRST_NAME
        scope: RUN_TIME
        value: "Admin"

      - key: SUPERSET_ADMIN_LAST_NAME
        scope: RUN_TIME
        value: "User"

      - key: SUPERSET_ADMIN_EMAIL
        scope: RUN_TIME
        value: "admin@insightpulseai.net"

      # Application
      - key: SUPERSET_LOAD_EXAMPLES
        scope: RUN_TIME
        value: "no"

      - key: SUPERSET_LOG_LEVEL
        scope: RUN_TIME
        value: "warning"

      - key: SUPERSET_WEBSERVER_PORT
        scope: RUN_TIME
        value: "8088"

    routes:
      - path: /superset
        preserve_path_prefix: false
