name: superset-analytics
region: sgp

services:
  - name: superset
    image:
      registry_type: DOCKER_HUB
      repository: apache/superset
      tag: "4.0.2"

    instance_size_slug: basic-xs
    instance_count: 1
    http_port: 8088

    run_command: |
      /bin/sh -c "superset db upgrade && superset fab create-admin --username admin --firstname Admin --lastname User --email admin@insightpulseai.net --password ${SUPERSET_ADMIN_PASSWORD} || true && superset init && /usr/bin/run-server.sh"

    health_check:
      http_path: /health
      initial_delay_seconds: 180
      period_seconds: 30
      timeout_seconds: 10

    envs:
      - key: SUPERSET_SECRET_KEY
        value: 8UToEhL2C0ovd7S4maFPsi7e4mU05pqAH907G5yUaLsr9prnJdHu7+6k
        scope: RUN_TIME
        type: SECRET

      - key: SUPERSET_ADMIN_PASSWORD
        value: SHWYXDMFAwXI1drT
        scope: RUN_TIME
        type: SECRET

      - key: DATABASE_DIALECT
        value: postgresql
        scope: RUN_TIME

      - key: DATABASE_HOST
        value: aws-0-us-east-1.pooler.supabase.com
        scope: RUN_TIME

      - key: DATABASE_PORT
        value: "6543"
        scope: RUN_TIME

      - key: DATABASE_DB
        value: postgres
        scope: RUN_TIME

      - key: DATABASE_USER
        value: postgres.spdtwktxdalcfigzeqrz
        scope: RUN_TIME

      - key: DATABASE_PASSWORD
        value: SHWYXDMFAwXI1drT
        scope: RUN_TIME
        type: SECRET

domains:
  - domain: superset.insightpulseai.net
    type: PRIMARY
