{
    "name": "IPAI Expense",
    "version": "19.0.20251026.1",
    "summary": "Cash advance lifecycle, expense policy, OCR audit",
    "author": "InsightPulseAI",
    "website": "https://insightpulseai.net/odoo/apps/ipai_expense",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "hr",
        "hr_expense",
        "account",
        "report_xlsx",
        "queue_job",
        "server_environment",
    ],
    "data": ["security/ir.model.access.csv", "data/sequence.xml"],
    "installable": True,
}
