# GitHub Labels Configuration for InsightPulse Odoo
# This file defines the labels used for issue and PR management

- name: "decision:sa"
  color: "0366d6"
  description: "Odoo SA implementation decision"

- name: "decision:oca"
  color: "6f42c1"
  description: "OCA module implementation decision"

- name: "decision:ipai"
  color: "d73a4a"
  description: "InsightPulse AI custom implementation"

- name: "area:bi"
  color: "0075ca"
  description: "Business Intelligence area"

- name: "area:crm"
  color: "cfd3d7"
  description: "CRM area"

- name: "area:procure"
  color: "a2eeef"
  description: "Procurement area"

- name: "area:expense"
  color: "7057ff"
  description: "Expense management area"

- name: "area:subscriptions"
  color: "008672"
  description: "Subscriptions area"

- name: "area:security"
  color: "e4e669"
  description: "Security area"

- name: "area:integration"
  color: "d876e3"
  description: "Integration area"

- name: "area:ml"
  color: "ffffff"
  description: "Machine Learning area"

- name: "area:agent"
  color: "006b75"
  description: "Agent system area"

- name: "status:analysis"
  color: "fbca04"
  description: "Under analysis"

- name: "status:ready"
  color: "0e8a16"
  description: "Ready for implementation"

- name: "status:in-progress"
  color: "1d76db"
  description: "Implementation in progress"

- name: "status:review"
  color: "5319e7"
  description: "Under review"

- name: "status:blocked"
  color: "b60205"
  description: "Blocked by dependencies"

- name: "status:completed"
  color: "c2e0c6"
  description: "Completed"

- name: "priority:critical"
  color: "b60205"
  description: "Critical priority"

- name: "priority:high"
  color: "d93f0b"
  description: "High priority"

- name: "priority:medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority:low"
  color: "0e8a16"
  description: "Low priority"

- name: "type:bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type:enhancement"
  color: "a2eeef"
  description: "New feature or improvement"

- name: "type:documentation"
  color: "0075ca"
  description: "Documentation improvements"

- name: "type:question"
  color: "d876e3"
  description: "Further information is requested"

- name: "type:security"
  color: "e4e669"
  description: "Security related issue"

- name: "type:performance"
  color: "008672"
  description: "Performance related issue"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "needs-triage"
  color: "fbca04"
  description: "Needs initial review and categorization"

- name: "superset-integration"
  color: "1d76db"
  description: "Related to Superset integration"

- name: "tableau-integration"
  color: "5319e7"
  description: "Related to Tableau integration"

- name: "microservices"
  color: "006b75"
  description: "Related to microservices architecture"

- name: "oca-modules"
  color: "6f42c1"
  description: "Related to OCA modules"

- name: "dev-agent"
  color: "d73a4a"
  description: "Related to development agents"

- name: "ci-cd"
  color: "0075ca"
  description: "Related to CI/CD pipeline"

- name: "testing"
  color: "fbca04"
  description: "Related to testing"

- name: "deployment"
  color: "0e8a16"
  description: "Related to deployment"
