name: insightpulse-monitor
region: sgp

services:
  - name: monitor
    github:
      repo: jgtolentino/insightpulse-odoo
      branch: main
      deploy_on_push: true
    source_dir: services/insightpulse-monitor
    dockerfile_path: services/insightpulse-monitor/Dockerfile

    http_port: 8000

    instance_count: 1
    instance_size_slug: basic-xxs

    health_check:
      http_path: /health
      initial_delay_seconds: 15
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    envs:
      # Supabase Configuration
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET

      - key: SUPABASE_SERVICE_KEY
        scope: RUN_TIME
        type: SECRET

      # Odoo Configuration
      - key: ODOO_URL
        scope: RUN_TIME
        type: SECRET

      - key: ODOO_DATABASE
        value: "postgres"
        scope: RUN_TIME

      - key: ODOO_API_KEY
        scope: RUN_TIME
        type: SECRET

      # Server Configuration
      - key: PORT
        value: "8000"
        scope: RUN_TIME

      - key: HOST
        value: "0.0.0.0"
        scope: RUN_TIME

      - key: LOG_LEVEL
        value: "INFO"
        scope: RUN_TIME

    routes:
      - path: /health
      - path: /mcp
      - path: /

# Optional: Add a custom domain
# domains:
#   - domain: monitor.insightpulseai.net
#     type: PRIMARY
