version: '3.8'

services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health', timeout=3.0)"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - insightpulse

networks:
  insightpulse:
    driver: bridge
