version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-odoo}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-odoo}"]
      interval: 10s
      timeout: 5s
      retries: 5
    platform: ${PLATFORM_DB:-}

  odoo:
    build:
      context: .
      args:
        ODOO_REF: ${ODOO_REF:-19.0}
    image: ${DOCKER_USER:-jgtolentino}/insightpulse-odoo:${ODOO_REF:-19.0}
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER:-odoo}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      DB_PORT: 5432
    ports: ["8069:8069"]
    volumes:
      - ./addons:/mnt/addons
    depends_on: [db]
    platform: ${PLATFORM_ODOO:-}

volumes:
  db: {}
