version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-odoo}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-odoo}"]
      interval: 10s
      timeout: 5s
      retries: 5
    platform: ${PLATFORM_DB:-}

  odoo:
    image: odoo:19
    environment:
      HOST: db
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    ports: ["8069:8069"]
    depends_on: [db]
    volumes:
      # InsightPulse modules (source display)
      - ./addons/insightpulse:/mnt/extra-addons/insightpulse
      # Custom modules (editable)
      - ./addons/custom:/mnt/extra-addons/custom
      # BI Superset agent
      - ./addons/bi_superset_agent:/mnt/extra-addons/bi_superset_agent
      # Knowledge Notion clone
      - ./addons/knowledge_notion_clone:/mnt/extra-addons/knowledge_notion_clone
      # OCA modules (read-only for safety)
      - ./addons/oca:/mnt/extra-addons/oca:ro
      # Configuration
      - ./config/odoo/odoo.conf:/etc/odoo/odoo.conf:ro
    platform: ${PLATFORM_ODOO:-}

volumes:
  db: {}

