name: Notebook CI

on:
  pull_request:
    paths:
      - "**/*.ipynb"
      - "tools/**"
      - ".github/workflows/notebook-ci.yml"
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort

      - name: Run Black (code formatting check)
        run: |
          black --check --diff tools/ || echo "::warning::Black found formatting issues in tools/"

      - name: Run Flake8 (linting)
        run: |
          flake8 tools/ --max-line-length=100 --extend-ignore=E203,W503 || echo "::warning::Flake8 found issues in tools/"

      - name: Run isort (import sorting)
        run: |
          isort --check-only --diff tools/ || echo "::warning::isort found issues in tools/"

  notebook-structure:
    name: Notebook Structure Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbclient jupyter

      - name: Make scripts executable
        run: chmod +x tools/notebook_test_runner.py tools/notebook_metadata_validator.py

      - name: Run structure tests
        run: |
          python tools/notebook_test_runner.py --mode structure --pattern "examples/**/*.ipynb"

  notebook-metadata:
    name: Validate Notebook Metadata
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat

      - name: Make scripts executable
        run: chmod +x tools/notebook_metadata_validator.py

      - name: Validate metadata
        run: |
          python tools/notebook_metadata_validator.py --pattern "examples/**/*.ipynb" --json-output metadata-report.json

      - name: Upload metadata report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metadata-report
          path: metadata-report.json
          retention-days: 30

  notebook-smoke-tests:
    name: Notebook Smoke Tests (Selected)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbclient jupyter openai

      - name: Check for API key
        id: check-key
        run: |
          if [[ -z "${{ secrets.OPENAI_API_KEY }}" ]]; then
            echo "has_key=false" >> $GITHUB_OUTPUT
            echo "⚠️ OPENAI_API_KEY not set - skipping smoke tests"
          else
            echo "has_key=true" >> $GITHUB_OUTPUT
          fi

      - name: Run smoke tests (if API key available)
        if: steps.check-key.outputs.has_key == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Only test a subset of notebooks in PR (to save API costs)
          # Adjust pattern as needed
          python tools/notebook_test_runner.py --mode smoke --pattern "examples/chat/basic_*.ipynb" --timeout 300

  generate-index:
    name: Generate Notebook Index
    runs-on: ubuntu-latest
    needs: [notebook-structure, notebook-metadata]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat

      - name: Generate notebook index
        run: |
          python tools/generate_notebook_index.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push index updates
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add notebook_index.json NOTEBOOK_INDEX.md notebook_stats.json examples/*/README.md
          git commit -m "docs: auto-update notebook index [skip ci]"
          git push

  comment-on-pr:
    name: Comment Test Results on PR
    runs-on: ubuntu-latest
    needs: [notebook-structure, notebook-metadata]
    if: github.event_name == 'pull_request' && always()

    steps:
      - name: Download metadata report
        uses: actions/download-artifact@v4
        with:
          name: metadata-report
        continue-on-error: true

      - name: Comment PR with results
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## 📓 Notebook Validation Results\\n\\n';

            // Check job statuses
            const structureStatus = '${{ needs.notebook-structure.result }}';
            const metadataStatus = '${{ needs.notebook-metadata.result }}';

            comment += `- Structure tests: ${structureStatus === 'success' ? '✅ PASS' : '❌ FAIL'}\\n`;
            comment += `- Metadata validation: ${metadataStatus === 'success' ? '✅ PASS' : '❌ FAIL'}\\n\\n`;

            // Read metadata report if available
            if (fs.existsSync('metadata-report.json')) {
              try {
                const report = JSON.parse(fs.readFileSync('metadata-report.json', 'utf8'));
                const totalNotebooks = Object.keys(report).length;
                const validNotebooks = Object.values(report).filter(r => r.valid).length;

                comment += `### Metadata Summary\\n`;
                comment += `- Total notebooks checked: ${totalNotebooks}\\n`;
                comment += `- Valid: ${validNotebooks}\\n`;
                comment += `- Invalid: ${totalNotebooks - validNotebooks}\\n`;
              } catch (e) {
                comment += `⚠️ Could not parse metadata report: ${e.message}\\n`;
              }
            }

            comment += '\\n---\\n';
            comment += 'Review the workflow logs for detailed information.';

            // Post comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
