name: mcp-github-server
region: sgp
services:
  - name: mcp-server
    source:
      repo: jgtolentino/insightpulse-odoo
      branch: feat/parity-live-sync
      deploy_on_push: true
    github:
      repo: jgtolentino/insightpulse-odoo
      branch: feat/parity-live-sync
      deploy_on_push: true
    dockerfile_path: services/mcp-server/Dockerfile
    source_dir: services/mcp-server
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: GITHUB_APP_ID
        value: "2191216"
      - key: GITHUB_INSTALLATION_ID
        value: "61508966"
      - key: GITHUB_REPO_OWNER
        value: "jgtolentino"
      - key: GITHUB_REPO_NAME
        value: "insightpulse-odoo"
      - key: GITHUB_PRIVATE_KEY
        scope: RUN_TIME
        type: SECRET
