# DigitalOcean App Platform Specification
# Multi-Agent Orchestrator Service
# Architecture: 6 AI agents (Orchestrator, Planner, Generator, Validator, Deployer, Monitor)
# Budget: $5/month (basic-xxs: 512MB RAM, 1 vCPU)
# URL: https://agents.insightpulseai.net

name: multi-agent-orchestrator
region: sgp  # Singapore for low latency

services:
  - name: odoo-developer-agent
    # GitHub source configuration
    github:
      repo: jgtolentino/insightpulse-odoo
      branch: main
      deploy_on_push: true

    # Source and build configuration
    source_dir: agents/mcp-servers/odoo-developer-agent
    dockerfile_path: agents/mcp-servers/odoo-developer-agent/Dockerfile
    build_command: ""

    # Instance configuration (basic-xxs: 512MB RAM, 1 vCPU, $5/month)
    instance_size_slug: basic-xxs
    instance_count: 1

    # HTTP configuration
    http_port: 8000

    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 20
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      # Supabase configuration (RAG knowledge base)
      - key: POSTGRES_URL
        scope: RUN_TIME
        type: SECRET
        # postgres://postgres.spdtwktxdalcfigzeqrz:PASSWORD@aws-1-us-east-1.pooler.supabase.com:6543/postgres

      - key: SUPABASE_URL
        scope: RUN_TIME
        value: "https://spdtwktxdalcfigzeqrz.supabase.co"

      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
        # Set in DO dashboard

      # GitHub integration
      - key: GITHUB_TOKEN
        scope: RUN_TIME
        type: SECRET
        # Set in DO dashboard

      # DigitalOcean API
      - key: DIGITALOCEAN_ACCESS_TOKEN
        scope: RUN_TIME
        type: SECRET
        # Set in DO dashboard

      # Odoo configuration
      - key: ODOO_URL
        scope: RUN_TIME
        value: "https://odoo-saas-platform-web.ondigitalocean.app"

      - key: ODOO_DB_NAME
        scope: RUN_TIME
        value: "postgres"

      - key: ODOO_ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
        # Set in DO dashboard

      # AI configuration (DigitalOcean Gradient AI)
      - key: AI_PROVIDER
        scope: RUN_TIME
        value: "anthropic"

      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
        # Set in DO dashboard

      - key: AI_MODEL
        scope: RUN_TIME
        value: "claude-sonnet-4-5-20250929"

      # Agent configuration
      - key: ENABLE_AUTO_FIX
        scope: RUN_TIME
        value: "true"

      - key: ENABLE_DEPLOYMENT
        scope: RUN_TIME
        value: "true"

      - key: ENABLE_MONITORING
        scope: RUN_TIME
        value: "true"

      # Deployment targets
      - key: DEPLOY_TARGET
        scope: RUN_TIME
        value: "docker"  # docker | digitalocean (NOT odoo.com per user requirement)

      # Paths
      - key: ODOO_ADDONS_PATH
        scope: RUN_TIME
        value: "/odoo/custom-addons"

      - key: TEMPLATES_PATH
        scope: RUN_TIME
        value: "/app/templates"

      # Logging
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: "INFO"

      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"

    # Routes configuration
    routes:
      - path: /
        preserve_path_prefix: true

# Custom domain configuration
domains:
  - domain: agents.insightpulseai.net
    type: PRIMARY

# =============================================================================
# Deployment Notes
# =============================================================================
#
# 1. Multi-Agent Architecture:
#    - Orchestrator: Master controller coordinating all agents
#    - Planner: Strategic planning and OCA compliance validation
#    - Generator: Template-based code generation (Jinja2)
#    - Validator: Linting, testing, security scanning (Black, Flake8, Pylint, Bandit)
#    - Deployer: Docker and DigitalOcean deployment automation
#    - Monitor: 4-point health checks and metrics collection
#
# 2. RAG Knowledge Base:
#    - Supabase pgvector (1536-dimension embeddings)
#    - 5 tables: knowledge_documents, knowledge_chunks, knowledge_embeddings,
#                knowledge_queries, knowledge_metadata
#    - Indexed Odoo 18 CE core modules
#
# 3. Set secrets in DigitalOcean dashboard:
#    - POSTGRES_URL (Supabase connection string with pooler port 6543)
#    - SUPABASE_SERVICE_ROLE_KEY (for Supabase API access)
#    - GITHUB_TOKEN (for GitHub integration)
#    - DIGITALOCEAN_ACCESS_TOKEN (for DO API calls)
#    - ODOO_ADMIN_PASSWORD (for Odoo API access)
#    - ANTHROPIC_API_KEY (Claude Sonnet 4.5 for orchestration)
#
# 4. Total cost estimate:
#    - odoo-developer-agent (basic-xxs: 512MB RAM): $5/month
#
# 5. Custom domain configuration:
#    - Domain: agents.insightpulseai.net
#    - DNS: CNAME record pointing to DO app URL
#    - HTTPS: Automatically enabled by DO App Platform
#
# 6. Deployment targets (per user requirement):
#    - ✅ insightpulseai.net
#    - ✅ Docker
#    - ✅ DigitalOcean
#    - ❌ NOT Odoo.com marketplace
#
# 7. Health checks:
#    - Endpoint: /health
#    - Initial delay: 30s (agent initialization)
#    - Interval: 20s
#    - Returns: {"status": "healthy", "agents": 6, "rag": "operational"}
#
# 8. Deployment commands:
#    # Create new app
#    doctl apps create --spec infra/do/multi-agent-orchestrator.yaml
#
#    # Update existing app
#    doctl apps update <APP_ID> --spec infra/do/multi-agent-orchestrator.yaml
#
#    # Get app ID
#    doctl apps list | grep multi-agent-orchestrator
#
# 9. Verification:
#    curl https://agents.insightpulseai.net/health
#    curl -X POST https://agents.insightpulseai.net/api/v1/generate \
#      -H "Content-Type: application/json" \
#      -d @test-spec.json
#
# 10. Performance:
#     - Module generation: <30 seconds
#     - Validation pipeline: <60 seconds
#     - Complete workflow: <2 minutes
#     - Cost savings: $238,600/year (vs manual development)
