name: pulser-hub-mcp
region: sgp
services:
- name: mcp-server
  github:
    repo: jgtolentino/insightpulse-odoo
    branch: main
    deploy_on_push: true
  source_dir: services/mcp-server
  run_command: uvicorn server:app --host 0.0.0.0 --port 8000
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 20
    period_seconds: 15
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: GITHUB_APP_ID
    value: "2191216"
  - key: GITHUB_PRIVATE_KEY
    scope: RUN_TIME
    type: SECRET
  - key: GITHUB_INSTALLATION_ID
    scope: RUN_TIME
    type: SECRET
  - key: LOG_LEVEL
    value: INFO
