# DigitalOcean App Platform Specification
# Pulse Hub Web UI - React + TypeScript + Vite
# Budget: $0/month (Static Site)

name: pulse-hub-web
region: sgp

static_sites:
  - name: pulse-hub
    # GitHub source configuration
    github:
      repo: jgtolentino/insightpulse-odoo
      branch: main
      deploy_on_push: true

    # Build configuration
    source_dir: pulse-hub
    build_command: npm ci && npm run build
    output_dir: dist

    # Environment variables for build
    envs:
      - key: VITE_GITHUB_APP_ID
        scope: BUILD_TIME
        value: "2191216"

      - key: VITE_MCP_SERVER_URL
        scope: BUILD_TIME
        value: "https://mcp.insightpulseai.net"

      - key: VITE_SUPABASE_URL
        scope: BUILD_TIME
        value: "https://spdtwktxdalcfigzeqrz.supabase.co"

      - key: VITE_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZHR3a3R4ZGFsY2ZpZ3plcXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NDQwMzUsImV4cCI6MjA3NjIyMDAzNX0.IHBJ0cNTMKJvRozljqaEqWph_gC0zlW2Td5Xl_GENs4"

    # Routes configuration (SPA routing)
    routes:
      - path: /
        preserve_path_prefix: false

    # Catchall route for SPA (redirect all routes to index.html)
    catchall_document: index.html
