version: "3.8"

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    restart: unless-stopped
    env_file:
      - ./superset.env
    ports:
      - "${SUPERSET_HOST_PORT:-8088}:8088"
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py:ro
    depends_on:
      - superset-db
      - superset-redis
    command: >
      sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        /usr/bin/run-server.sh
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  superset-db:
    image: postgres:15
    container_name: superset-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SUPERSET_POSTGRES_DB:-superset}
      POSTGRES_USER: ${SUPERSET_POSTGRES_USER:-superset}
      POSTGRES_PASSWORD: ${SUPERSET_POSTGRES_PASSWORD}
    volumes:
      - superset_db:/var/lib/postgresql/data
      - ./sql/superset_dsn_seeder.sql:/docker-entrypoint-initdb.d/01-seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SUPERSET_POSTGRES_USER:-superset}"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset-redis:
    image: redis:7-alpine
    container_name: superset-redis
    restart: unless-stopped
    volumes:
      - superset_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  superset_home:
  superset_db:
  superset_redis:
