# Docker Compose addition for Superset BI Agent
# To integrate: merge this into bundle/docker-compose.yml

version: '3.8'

services:
  # Apache Superset
  superset:
    image: apache/superset:latest
    container_name: bundle-superset-1
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY:-CHANGE_ME_TO_RANDOM_64_CHAR_STRING}
      - DATABASE_URL=postgresql://odoo:${DB_PASSWORD}@postgres:5432/superset
      - REDIS_URL=redis://redis:6379/1
      - SUPERSET_ENV=production
      - SUPERSET_LOAD_EXAMPLES=no
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - redis
    networks:
      - odoo_network
    volumes:
      - superset_home:/app/superset_home
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      bash -c "
      superset db upgrade &&
      superset init &&
      gunicorn --bind 0.0.0.0:8088 --workers 4 --timeout 120 --limit-request-line 0 --limit-request-field_size 0 'superset.app:create_app()'
      "

  # BI Agent (FastAPI service)
  bi-agent:
    build:
      context: ./superset-bi-agent
      dockerfile: Dockerfile
    container_name: bundle-bi-agent-1
    environment:
      - SUPERSET_URL=http://superset:8088
      - SUPERSET_USERNAME=${SUPERSET_USERNAME:-admin}
      - SUPERSET_PASSWORD=${SUPERSET_PASSWORD:-admin}
      - SUPERSET_PROVIDER=db
      - DATASET_ID=1
      - ODOO_DB_URL=postgresql://odoo:${DB_PASSWORD}@postgres:5432/odoo
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o-mini
      - REDIS_URL=redis://redis:6379/2
    ports:
      - "8001:8001"
    depends_on:
      - superset
      - postgres
      - redis
    networks:
      - odoo_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  superset_home:
    driver: local

networks:
  odoo_network:
    external: true
