[project]
name = "odoo-addons-oca-server-tools"
version = "18.0.20251016.0"
dependencies = [
    "odoo-addon-attachment_queue==18.0.*",
    "odoo-addon-attachment_synchronize==18.0.*",
    "odoo-addon-attachment_unindex_content==18.0.*",
    "odoo-addon-auditlog==18.0.*",
    "odoo-addon-auto_backup==18.0.*",
    "odoo-addon-autovacuum_message_attachment==18.0.*",
    "odoo-addon-base_cron_exclusion==18.0.*",
    "odoo-addon-base_exception==18.0.*",
    "odoo-addon-base_fontawesome==18.0.*",
    "odoo-addon-base_force_record_noupdate==18.0.*",
    "odoo-addon-base_m2m_custom_field==18.0.*",
    "odoo-addon-base_model_restrict_update==18.0.*",
    "odoo-addon-base_name_search_improved==18.0.*",
    "odoo-addon-base_partition==18.0.*",
    "odoo-addon-base_remote==18.0.*",
    "odoo-addon-base_search_fuzzy==18.0.*",
    "odoo-addon-base_sequence_option==18.0.*",
    "odoo-addon-base_sparse_field_list_support==18.0.*",
    "odoo-addon-base_technical_user==18.0.*",
    "odoo-addon-base_time_window==18.0.*",
    "odoo-addon-base_view_inheritance_extension==18.0.*",
    "odoo-addon-database_cleanup==18.0.*",
    "odoo-addon-database_size==18.0.*",
    "odoo-addon-dbfilter_from_header==18.0.*",
    "odoo-addon-fetchmail_attach_from_folder==18.0.*",
    "odoo-addon-fetchmail_notify_error_to_sender==18.0.*",
    "odoo-addon-html_text==18.0.*",
    "odoo-addon-iap_alternative_provider==18.0.*",
    "odoo-addon-jsonifier==18.0.*",
    "odoo-addon-mail_cleanup==18.0.*",
    "odoo-addon-module_auto_update==18.0.*",
    "odoo-addon-module_change_auto_install==18.0.*",
    "odoo-addon-onchange_helper==18.0.*",
    "odoo-addon-rpc_helper==18.0.*",
    "odoo-addon-scheduler_error_mailer==18.0.*",
    "odoo-addon-sentry==18.0.*",
    "odoo-addon-session_db==18.0.*",
    "odoo-addon-test_auditlog==18.0.*",
    "odoo-addon-test_base_time_window==18.0.*",
    "odoo-addon-tracking_manager==18.0.*",
    "odoo-addon-tracking_manager_domain==18.0.*",
    "odoo-addon-upgrade_analysis==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
