#!/usr/bin/env bash
#
# update-auto-sections.sh
# Updates auto-generated sections in documentation files
#
# This script:
# - Updates timestamps in all docs
# - Generates MODULE_INDEX.md
# - Updates cross-reference sections
# - Safe to run anytime

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔄 Updating Auto-Generated Documentation Sections..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

CURRENT_DATE=$(date +%Y-%m-%d)

# 1. Update timestamps in key documentation files
echo "1️⃣  Updating timestamps..."

for file in claude.md .github/PLANNING.md DOCUMENTATION_SYSTEM.md; do
    if [[ -f "$file" ]]; then
        if grep -q "Last Updated:" "$file" || grep -q "Last Auto-Updated:" "$file"; then
            # Update existing timestamp
            if [[ "$OSTYPE" == "darwin"* ]]; then
                # macOS
                sed -i '' "s/Last Updated:.*/Last Updated:** $CURRENT_DATE/" "$file"
                sed -i '' "s/Last Auto-Updated:.*/Last Auto-Updated:** $CURRENT_DATE/" "$file"
            else
                # Linux
                sed -i "s/Last Updated:.*/Last Updated:** $CURRENT_DATE/" "$file"
                sed -i "s/Last Auto-Updated:.*/Last Auto-Updated:** $CURRENT_DATE/" "$file"
            fi
            echo -e "   ${GREEN}✅ Updated timestamp in $file${NC}"
        fi
    fi
done
echo ""

# 2. Generate MODULE_INDEX.md
echo "2️⃣  Generating MODULE_INDEX.md..."

mkdir -p docs

cat > docs/MODULE_INDEX.md <<'EOF'
# Module Documentation Index
**Auto-Generated:** Do not edit manually
**Last Updated:** $(date +%Y-%m-%d)

This file is automatically generated by `scripts/update-auto-sections.sh`.

---

## Module Documentation Coverage

EOF

if [[ -d "odoo/addons" ]]; then
    TOTAL=0
    WITH_DOCS=0
    MISSING=()

    echo "| Module | README | Description |" >> docs/MODULE_INDEX.md
    echo "|--------|--------|-------------|" >> docs/MODULE_INDEX.md

    for module in odoo/addons/*; do
        if [[ -d "$module" ]] && [[ -f "$module/__manifest__.py" ]]; then
            TOTAL=$((TOTAL + 1))
            MODULE_NAME=$(basename "$module")

            # Extract description from __manifest__.py
            DESCRIPTION=$(grep -m1 "'summary':" "$module/__manifest__.py" 2>/dev/null | sed "s/.*'summary':\s*'\(.*\)'.*/\1/" || echo "N/A")

            if [[ -f "$module/README.md" ]]; then
                WITH_DOCS=$((WITH_DOCS + 1))
                echo "| [$MODULE_NAME](../odoo/addons/$MODULE_NAME) | ✅ | $DESCRIPTION |" >> docs/MODULE_INDEX.md
            else
                MISSING+=("$MODULE_NAME")
                echo "| $MODULE_NAME | ❌ | $DESCRIPTION |" >> docs/MODULE_INDEX.md
            fi
        fi
    done

    echo "" >> docs/MODULE_INDEX.md
    echo "## Statistics" >> docs/MODULE_INDEX.md
    echo "" >> docs/MODULE_INDEX.md
    echo "- **Total Modules:** $TOTAL" >> docs/MODULE_INDEX.md
    echo "- **Documented:** $WITH_DOCS" >> docs/MODULE_INDEX.md

    if [[ $TOTAL -gt 0 ]]; then
        COVERAGE=$(( WITH_DOCS * 100 / TOTAL ))
        echo "- **Coverage:** $COVERAGE%" >> docs/MODULE_INDEX.md
    fi

    if [[ ${#MISSING[@]} -gt 0 ]]; then
        echo "" >> docs/MODULE_INDEX.md
        echo "## Missing Documentation" >> docs/MODULE_INDEX.md
        echo "" >> docs/MODULE_INDEX.md
        for mod in "${MISSING[@]}"; do
            echo "- [ ] $mod" >> docs/MODULE_INDEX.md
        done
    fi

    echo "" >> docs/MODULE_INDEX.md
    echo "---" >> docs/MODULE_INDEX.md
    echo "" >> docs/MODULE_INDEX.md
    echo "**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> docs/MODULE_INDEX.md
    echo "**Script:** \`scripts/update-auto-sections.sh\`" >> docs/MODULE_INDEX.md

    echo -e "   ${GREEN}✅ Generated MODULE_INDEX.md ($TOTAL modules)${NC}"
else
    echo "No modules found" >> docs/MODULE_INDEX.md
    echo -e "   ${YELLOW}⚠️  odoo/addons directory not found${NC}"
fi
echo ""

# 3. Update cross-references section in README.md (if marker exists)
echo "3️⃣  Updating cross-references..."

if [[ -f "README.md" ]]; then
    # Check if README has a cross-reference section
    if ! grep -q "claude.md" README.md; then
        echo -e "   ${YELLOW}ℹ️  Add cross-reference to claude.md manually${NC}"
    else
        echo -e "   ${GREEN}✅ Cross-reference to claude.md exists${NC}"
    fi
fi

if [[ -f "claude.md" ]]; then
    if ! grep -q "README.md" claude.md; then
        echo -e "   ${YELLOW}ℹ️  Add cross-reference to README.md manually${NC}"
    else
        echo -e "   ${GREEN}✅ Cross-reference to README.md exists${NC}"
    fi
fi
echo ""

# 4. Ensure CHANGELOG.md exists
echo "4️⃣  Checking CHANGELOG.md..."

if [[ ! -f "CHANGELOG.md" ]]; then
    cat > CHANGELOG.md <<'EOF'
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Living documentation system with automated validation
- Documentation automation workflows
- Module documentation index generation

---

<!-- Generated by scripts/update-auto-sections.sh -->
EOF
    echo -e "   ${GREEN}✅ Created CHANGELOG.md${NC}"
else
    echo -e "   ${GREEN}✅ CHANGELOG.md exists${NC}"
fi
echo ""

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Documentation Update Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅ Auto-generated sections updated successfully${NC}"
echo ""
echo "Files modified:"
echo "  - docs/MODULE_INDEX.md"
echo "  - Timestamps in claude.md, PLANNING.md"
echo ""
echo "Next steps:"
echo "  git add docs/ *.md .github/PLANNING.md"
echo "  git commit -m 'docs: auto-update generated sections'"
