name: Lint & Compose dry-run
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate compose
        run: docker compose -f docker-compose.yml config
      - name: Odoo manifest lint (basic)
        run: |
          python - <<'PY'
import os, sys, json
bad=[]
for root,_,files in os.walk('addons'):
  if '__manifest__.py' in files:
    try: exec(open(os.path.join(root,'__manifest__.py')).read(),{})
    except Exception as e: bad.append((root,str(e)))
print("OK" if not bad else bad); sys.exit(0 if not bad else 1)
PY
