name: docker

on:
  push:
    branches: [main]
    tags: ['v*', 'release-*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Buildx (Docker Build Cloud)
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: jgtolentino/odoobo

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            ODOO_REF=19.0
          tags: |
            ${{ vars.DOCKER_USER }}/insightpulse-odoo:latest
            ${{ vars.DOCKER_USER }}/insightpulse-odoo:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
