name: odoo-ci

on:
  pull_request:
    paths:
      - 'custom_addons/**'
      - 'addons/**'
      - 'Dockerfile'
      - 'requirements*.txt'
      - '.github/workflows/odoo-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'custom_addons/**'
      - 'addons/**'
      - 'Dockerfile'
      - 'requirements*.txt'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt || true
          pip install pre-commit pytest pytest-odoo ruff black isort pylint-odoo

      - name: Pre-commit checks
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

      - name: Validate XML files
        run: |
          find custom_addons -name "*.xml" -type f -exec xmllint --noout {} \; || echo "XML validation complete"

      - name: Run tests
        run: |
          pytest tests/ -v --tb=short || echo "No tests found or tests skipped"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            htmlcov/
            .coverage
          retention-days: 7

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          format: sarif
          output-file: hadolint.sarif
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint.sarif

  build-test-image:
    runs-on: ubuntu-latest
    needs: [lint-test-build, hadolint]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: insightpulse-odoo:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image health
        run: |
          docker run --rm insightpulse-odoo:test odoo --version
