name: post-deploy-refresh
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["dockerhub-publish", "docker-build"]
    types: [completed]
permissions: { contents: read }
jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and refresh on droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -e
            cd ~/insightpulse-odoo

            echo "🐳 Pulling latest Docker images from registry..."
            docker compose pull odoo

            echo "🚀 Restarting services with new images..."
            docker compose up -d --force-recreate odoo

            DB="${{ secrets.ODOO_DB }}"
            echo "🔄 Updating Odoo modules..."
            docker compose exec -T odoo odoo shell -d "$DB" -c "env['ir.module.module'].update_list()"

            echo "🔄 Upgrading all modules..."
            docker compose exec -T odoo odoo -c /etc/odoo/odoo.conf -d "$DB" -u all --stop-after-init

            echo "✅ Docker registry deployment completed successfully!"
