name: Code Quality

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Pre-commit checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  pylint-odoo:
    runs-on: ubuntu-latest
    name: Pylint Odoo checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint-odoo
          pip install -r requirements.txt

      - name: Run pylint-odoo
        run: |
          find addons -name '*.py' -not -path '*/tests/*' | xargs pylint --load-plugins=pylint_odoo -d all -e odoolint || true

  flake8-odoo:
    runs-on: ubuntu-latest
    name: Flake8 checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 addons --max-line-length=88 --extend-ignore=E203,E501,W503

  security:
    runs-on: ubuntu-latest
    name: Security scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run bandit
        run: |
          bandit -r addons -x */tests/* -ll || true

      - name: Check for vulnerable dependencies
        run: |
          pip install -r requirements.txt
          safety check || true
