name: Seed Labels

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/labels.yml"

permissions:
  contents: read
  issues: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: false
